		// dsh-skip-func-length（identityCSS 巨型函数 248 行，函数级拆分列为后续优化项，本次仅文件级拆分）
		// ═══════════ 3. 身份层 CSS ═══════════
		function identityCSS() {
			const tokenLines = Object.entries(TOKENS)
				.map(([name, value]) => "  " + name + ": " + value + " !important;")
				.join("\n");
			return [
				// 中间背景不改：html 不再用主题纯色铺满（去雾），透明让壁纸层 .ff-bg 透出；兜底深色只在无壁纸时可见
				"html { color-scheme: dark !important; background: #0a0c12 !important;",
"  /* ── 基底主题变量（壁纸联动皮肤命名空间 --ff-theme-*；值=一键应用配色，动态取色覆盖）── */",
"  /* 一键应用 知更鸟晴歌当前样式备份：肤色 E8F4FA / 发色 E2C05A / 瞳色 D8EAF4 / 礼服灰白 E2C05A / 礼服紫 E2C05A / 点缀金 E2C05A */",
"  --ff-theme-bg: 62, 47, 102;",
"  --ff-theme-bg-soft: 42, 33, 72;",
"  --ff-theme-bg-layer: 54, 42, 86;",
"  --ff-theme-accent: 216, 234, 244;",
"  --ff-theme-accent-soft: 226, 192, 90;",
"  --ff-theme-text: 232, 244, 250;",
"  --ff-theme-text-dim: 226, 192, 90;",
"  --ff-theme-border: 226, 192, 90;",
"}",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
				"body {",
				"  background-color: transparent !important;",
				"  color: rgb(var(--ff-theme-text));",
				"  --dsw-font-family: 'MiSans', 'PingFang SC', 'Microsoft YaHei', -apple-system, 'Segoe UI', sans-serif;",
				"  --ds-font-family-code: 'SF Mono', 'JetBrains Mono', Consolas, Menlo, 'PingFang SC', monospace;",
				tokenLines,
				"}",
				// 全局文字轻描边：中间画面全透明后文字直接叠在壁纸上，黑色描边保证任何壁纸下可读
				// （轻描边：下方 1px + 四周微晕；具体元素可覆盖，见 .ff-music-lbl/.ff-title 的辉光叠加）
				"* { text-shadow: 0 1px 1px rgba(0, 0, 0, 0.5), 0 0 2px rgba(0, 0, 0, 0.75), 1px 0 1px rgba(0, 0, 0, 0.45), -1px 0 1px rgba(0, 0, 0, 0.45) !important; }",
				// 中间会话窗口轻毛玻璃（只消息列表 + 轻 blur 6px）：DSH 主会话容器
				// 加 backdrop-filter 背景模糊 + 微半透明，壁纸透出但文字清晰；不动 bg-base 的透明策略
				"[class*='_float_'] { backdrop-filter: blur(6px) saturate(130%); -webkit-backdrop-filter: blur(6px) saturate(130%); background-color: rgba(10, 12, 18, 0.22) !important; }",
				// 模态遮罩去模糊：打开设置/弹层时覆盖全屏的 _mask 层（背景 var(--dsw-alias-bg-mask-1) +
				// backdrop-filter var(--dsw-mask-blur)），关掉其背景模糊并保持透明，壁纸全屏透出；
				// mask 颜色透明化已在 tokens（0.25），这里处理宿主注入的 blur 默认值
				"[class*='_mask_'] { backdrop-filter: none !important; -webkit-backdrop-filter: none !important; background-color: rgba(10, 12, 18, 0.18) !important; }",
				// 中间会话区文字放大：会话主容器字号基准 14px→16px（继承式，未显式设字号的正文跟随放大，
				// 显式 11/12px 的小标签/时间戳保持原样；行高同步 22px→26px）
				// 「字」按钮通过 --ff-font-scale 缩放（0.85/1/1.15/1.3），calc() 复合实现全界面字号调节
				"[class*='_float_'] { font-size: calc(16px * var(--ff-font-scale, 1)) !important; }",
				"[class*='_float_'] [class*='_'] { line-height: calc(26px * var(--ff-font-scale, 1)) !important; }",
				// 「深度求索中…」状态提示（AI 处理中）：小胶囊 + 字号加大 + 白描边（叠加在全局黑描边之上，
				// 深色胶囊底保证任意壁纸下白描边清晰；锚点 role="status" 稳定不随 CSS Modules hash 变化）
				"[role='status'] { display: inline-flex; align-items: center; gap: 6px; padding: 4px 14px;",
				"  border-radius: 999px; font-size: calc(16px * var(--ff-font-scale, 1)) !important; line-height: calc(22px * var(--ff-font-scale, 1)); font-weight: 600;",
				"  color: #F5F7FA !important; background: rgba(124, 120, 190, 0.6) !important;",
				"  -webkit-text-stroke: 1px rgba(255, 255, 255, 0.85); text-shadow: none !important; }",
				"[role='status'] [class*='_'] { text-shadow: inherit !important; }",

				// 壁纸背景层（z -2）+ 可读性遮罩（z -1）
				".ff-bg { position: fixed; inset: 0; z-index: -2; pointer-events: none; overflow: hidden;",
				"  background-color: transparent; background-position: center; background-size: cover; background-repeat: no-repeat; }",
				".ff-bg video { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; }",

				"::selection { background: rgba(var(--ff-theme-accent),  0.25); color: rgb(var(--ff-theme-text)); }",

				// 萤火氛围粒子（分档：关/星点/曳光/流萤，数量渐变）
				".ff-amb { position: fixed; inset: 0; pointer-events: none; z-index: 60; overflow: hidden; }",
				".ff-amb i { position: absolute; bottom: -14px; left: 0; opacity: 0;",
				"  transition: opacity 0.9s ease;",
				"  animation: ffFloat var(--dur, 20s) linear var(--delay, -5s) infinite;",
				"  will-change: transform, opacity; }",
				".ff-amb i.on { opacity: 1; }",
				".ff-amb i span { display: block; border-radius: 50%; background: rgb(var(--ff-theme-accent));",
				"  box-shadow: 0 0 8px 2px rgba(var(--ff-theme-border), 0.55); opacity: var(--op, 0.6);",
				"  animation: ffTwinkle 3.2s ease-in-out infinite; }",
				"@keyframes ffTwinkle { 0%, 100% { opacity: calc(var(--op, 0.6) * 0.45); } 50% { opacity: var(--op, 0.6); } }",
				"@keyframes ffFloat { 0% { transform: translate3d(0, 0, 0); }",
				"  100% { transform: translate3d(var(--drift, 24px), -110vh, 0); } }",
				// 右下角可拖动工具条（毛玻璃竖条圆角，位置记忆；竖排：字/景/声/乐）
				".ff-dock { position: fixed; right: 12px; bottom: 12px; z-index: 90; display: flex; flex-direction: column; align-items: center; gap: 7px;",
				"  padding: 6px 8px; border-radius: 14px; background: rgba(var(--ff-theme-bg-layer),  0.42);",
				"  border: 1px solid rgba(var(--ff-theme-border),  0.28); box-shadow: 0 6px 24px rgba(0, 0, 0, 0.35);",
				"  backdrop-filter: blur(14px) saturate(150%); -webkit-backdrop-filter: blur(14px) saturate(150%);",
				"  cursor: grab; user-select: none; -webkit-user-select: none; touch-action: none; }",
				".ff-dock.dragging { cursor: grabbing; }",
				".ff-dock-btn { width: 30px; height: 30px; border-radius: 50%; font-size: 13px; line-height: 1;",
				"  color: rgba(var(--ff-theme-text-dim),  0.75); background: rgba(var(--ff-theme-bg-layer),  0.5);",
				"  border: 1px solid rgba(var(--ff-theme-border),  0.35); cursor: pointer; opacity: 0.55; padding: 0;",
				"  transition: opacity 0.15s ease, color 0.15s ease, background 0.15s ease; }",
				".ff-dock-btn:hover { opacity: 1; }",
				".ff-music-toggle.on, .ff-bg-toggle.on, .ff-font-toggle.on { opacity: 1; color: rgb(var(--ff-theme-accent)); box-shadow: 0 0 10px rgba(var(--ff-theme-accent),  0.4); }",
				".ff-snd-toggle.on { opacity: 1; color: rgb(var(--ff-theme-accent)); box-shadow: 0 0 10px rgba(var(--ff-theme-accent),  0.4); }",
				".ff-snd-menu { position: absolute; right: 0; bottom: calc(100% + 8px); z-index: 92; display: none; flex-direction: column;",
				"  gap: 8px; min-width: 188px; background: rgba(var(--ff-theme-bg-layer), 0.9); border: 1px solid rgba(var(--ff-theme-border), 0.35);",
				"  border-radius: 10px; padding: 10px 12px; box-shadow: 0 6px 24px rgba(0,0,0,0.4); backdrop-filter: blur(6px); }",
				".ff-snd-menu.open { display: flex; }",
				".ff-snd-line { display: flex; align-items: center; gap: 8px; }",
				".ff-snd-label { font-size: 12px; color: rgba(var(--ff-theme-text-dim), 0.75); min-width: 60px; }",
				".ff-snd-toggle-box { position: relative; width: 34px; height: 18px; border-radius: 999px; cursor: pointer;",
				"  background: rgba(var(--ff-theme-accent), 0.14); border: 1px solid rgba(var(--ff-theme-border), 0.4); transition: background 0.15s ease; }",
				".ff-snd-toggle-box::after { content: \"\"; position: absolute; top: 2px; left: 2px; width: 12px; height: 12px;",
				"  border-radius: 50%; background: rgba(var(--ff-theme-text-dim), 0.8); transition: transform 0.15s ease, background 0.15s ease; }",
				".ff-snd-toggle-box.on { background: rgba(var(--ff-theme-accent), 0.45); }",
				".ff-snd-toggle-box.on::after { transform: translateX(16px); background: rgb(var(--ff-theme-text)); }",
				".ff-snd-vol { flex: 1; height: 26px; min-width: 0; accent-color: rgb(var(--ff-theme-accent)); cursor: pointer; }",
				".ff-snd-vol-ico { width: 22px; height: 22px; border-radius: 50%; border: 1px solid rgba(var(--ff-theme-border), 0.35);",
				"  background: rgba(var(--ff-theme-accent), 0.07); color: rgba(var(--ff-theme-text), 0.9); cursor: pointer; font-size: 13px; line-height: 20px;",
				"  padding: 0; text-align: center; transition: background 0.15s ease; opacity: 0.75; }",
				".ff-snd-vol-ico:hover { background: rgba(var(--ff-theme-accent), 0.18); opacity: 1; }",
				".ff-snd-vol-ico.on { opacity: 1; color: rgb(var(--ff-theme-accent)); box-shadow: 0 0 10px rgba(var(--ff-theme-accent),  0.4); }",
				".ff-font-menu { position: absolute; right: 0; bottom: calc(100% + 8px); z-index: 92; display: none; flex-direction: column;",
				"  gap: 5px; background: rgba(var(--ff-theme-bg-layer), 0.88); border: 1px solid rgba(var(--ff-theme-border), 0.35);",
				"  border-radius: 10px; padding: 7px; box-shadow: 0 6px 24px rgba(0,0,0,0.4); }",
				".ff-font-menu.open { display: flex; }",
				".ff-font-opt { min-width: 64px; height: 26px; border-radius: 6px; border: 1px solid rgba(var(--ff-theme-border), 0.25);",
				"  background: rgba(var(--ff-theme-accent), 0.07); color: rgba(var(--ff-theme-text), 0.88); cursor: pointer; font-size: 12px; padding: 0 8px; }",
				".ff-font-opt:hover { background: rgba(var(--ff-theme-accent), 0.16); }",
				".ff-font-opt.active { background: rgba(var(--ff-theme-accent), 0.22); color: rgb(var(--ff-theme-accent)); border-color: rgba(var(--ff-theme-border), 0.55); }",
				".ff-bg-panel { position: absolute; right: 0; bottom: calc(100% + 8px); z-index: 92; display: none; flex-direction: column;",
				"  gap: 8px; min-width: 212px; background: rgba(var(--ff-theme-bg-layer), 0.9); border: 1px solid rgba(var(--ff-theme-border), 0.35);",
				"  border-radius: 10px; padding: 10px 12px; box-shadow: 0 6px 24px rgba(0,0,0,0.4); backdrop-filter: blur(6px); }",
				".ff-bg-panel.open { display: flex; }",
				".ff-bg-title { font-size: 12px; letter-spacing: 2px; color: rgba(var(--ff-theme-text-dim), 0.85); }",
				".ff-bg-line { display: flex; align-items: center; gap: 6px; }",
				".ff-bg-label { font-size: 12px; color: rgba(var(--ff-theme-text-dim), 0.7); min-width: 52px; }",
				".ff-bg-seg { flex: 1; height: 26px; border-radius: 6px; border: 1px solid rgba(var(--ff-theme-border), 0.25);",
				"  background: rgba(var(--ff-theme-accent), 0.07); color: rgba(var(--ff-theme-text), 0.88); cursor: pointer; font-size: 12px; padding: 0 6px; }",
				".ff-bg-seg:hover { background: rgba(var(--ff-theme-accent), 0.16); }",
				".ff-bg-seg.active { background: rgba(var(--ff-theme-accent), 0.24); color: rgb(var(--ff-theme-accent)); border-color: rgba(var(--ff-theme-border), 0.55); }",
				".ff-bg-seg:disabled { opacity: 0.32; cursor: not-allowed; }",
				".ff-bg-interval { flex: 1; height: 26px; min-width: 0; border-radius: 6px; border: 1px solid rgba(var(--ff-theme-border), 0.25);",
				"  background: rgba(var(--ff-theme-accent), 0.07); color: rgba(var(--ff-theme-text), 0.95); font-size: 12px; padding: 0 8px; }",
				".ff-bg-unit { font-size: 12px; color: rgba(var(--ff-theme-text-dim), 0.7); }",
				".ff-bg-ok { height: 28px; border-radius: 6px; border: 1px solid rgba(var(--ff-theme-border), 0.4);",
				"  background: rgba(var(--ff-theme-accent), 0.16); color: #c9ffe0; cursor: pointer; font-size: 13px; }",
				".ff-bg-ok:hover { background: rgba(var(--ff-theme-accent), 0.26); }",
				".ff-bg-add { height: 28px; border-radius: 6px; border: 1px dashed rgba(var(--ff-theme-border), 0.45);",
				"  background: transparent; color: rgba(var(--ff-theme-text), 0.85); cursor: pointer; font-size: 13px; }",
				".ff-bg-add:hover { background: rgba(var(--ff-theme-accent), 0.12); }",
				".ff-bg-picker { position: absolute; right: 0; bottom: calc(100% + 8px); z-index: 93; display: none; flex-direction: column;",
				"  gap: 8px; width: 430px; max-width: calc(100vw - 24px); max-height: calc(100vh - 80px); background: rgba(var(--ff-theme-bg-layer), 0.95);",
				"  border: 1px solid rgba(var(--ff-theme-border), 0.35); border-radius: 10px; padding: 10px; box-shadow: 0 6px 24px rgba(0,0,0,0.45); }",
				".ff-bg-picker.open { display: flex; }",
				".ff-bg-picker-head { display: flex; align-items: center; justify-content: space-between; gap: 8px; }",
				".ff-bg-picker-title { font-size: 12px; letter-spacing: 2px; color: rgba(var(--ff-theme-text-dim), 0.85); }",
				".ff-bg-close { width: 20px; height: 20px; border-radius: 5px; border: 1px solid rgba(var(--ff-theme-border), 0.3);",
				"  background: rgba(var(--ff-theme-accent), 0.08); color: rgba(var(--ff-theme-text), 0.85); cursor: pointer; font-size: 12px; line-height: 1; padding: 0; }",
				".ff-bg-close:hover { background: rgba(var(--ff-theme-accent), 0.2); color: rgb(var(--ff-theme-text)); }",
				".ff-bg-picker-list { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; align-content: start;",
				"  max-height: min(690px, calc(100vh - 210px)); overflow-y: auto; overscroll-behavior: contain; padding-right: 2px;",
				"  scrollbar-width: thin; scrollbar-color: rgba(var(--ff-theme-accent), 0.35) rgba(255,255,255,0.04); }",
				".ff-bg-picker-list::-webkit-scrollbar { width: 8px; }",
				".ff-bg-picker-list::-webkit-scrollbar-track { background: rgba(255,255,255,0.04); border-radius: 8px; }",
				".ff-bg-picker-list::-webkit-scrollbar-thumb { background: rgba(var(--ff-theme-accent), 0.35); border-radius: 8px; }",
				".ff-bg-picker-list::-webkit-scrollbar-thumb:hover { background: rgba(var(--ff-theme-accent), 0.55); }",
				".ff-bg-picker-empty { grid-column: 1 / -1; text-align: center; color: rgba(var(--ff-theme-text-dim), 0.55); font-size: 12px; padding: 30px 0; }",
				".ff-bg-picker-item { position: relative; display: flex; flex-direction: column; gap: 4px; align-items: center; background: transparent;",
				"  min-width: 0; border: 1px solid rgba(var(--ff-theme-border), 0.2); border-radius: 8px; padding: 4px; cursor: pointer;",
				"  color: rgba(var(--ff-theme-text), 0.85); font-size: 11px; transition: border-color 0.15s ease, background 0.15s ease; }",
				".ff-bg-picker-item:hover { border-color: rgba(var(--ff-theme-border), 0.55); background: rgba(var(--ff-theme-accent), 0.1); }",
				".ff-bg-picker-item.checked { border-color: rgb(var(--ff-theme-accent)); background: rgba(var(--ff-theme-accent), 0.14); box-shadow: 0 0 10px rgba(var(--ff-theme-accent), 0.2); }",
				".ff-bg-picker-item img, .ff-bg-picker-item video { width: 100%; height: auto; aspect-ratio: 1 / 1; object-fit: cover; border-radius: 5px; background: rgb(var(--ff-theme-bg)); }",
				".ff-bg-picker-item span { max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; line-height: 14px; height: 14px; }",
				".ff-bg-check { position: absolute; top: 6px; right: 6px; width: 16px; height: 16px; margin: 0; cursor: pointer;",
				"  accent-color: rgb(var(--ff-theme-accent-soft)); z-index: 2; }",
				".ff-bg-picker-actions { display: flex; gap: 8px; }",
				".ff-bg-act { flex: 1; height: 28px; border-radius: 6px; border: 1px solid rgba(var(--ff-theme-border), 0.35);",
				"  background: rgba(var(--ff-theme-accent), 0.1); color: rgba(var(--ff-theme-text), 0.9); cursor: pointer; font-size: 12px; }",
				".ff-bg-act:hover:not(:disabled) { background: rgba(var(--ff-theme-accent), 0.22); }",
				".ff-bg-act:disabled { opacity: 0.35; cursor: not-allowed; }",
				".ff-bg-act.ff-bg-remove { color: #ffb3c0; border-color: rgba(255,93,122,0.4); background: rgba(255,93,122,0.1); }",
				".ff-bg-act.ff-bg-remove:hover:not(:disabled) { background: rgba(255,93,122,0.22); }",
				".ff-music-card { position: absolute; right: 0; bottom: calc(100% + 8px); z-index: 91; width: 252px; max-width: calc(100vw - 24px);",
				"  background: rgba(var(--ff-theme-bg-layer), 0.85); border: 1px solid rgba(var(--ff-theme-border), 0.35); border-radius: 10px;",
				"  padding: 10px 12px; box-sizing: border-box; display: flex; flex-direction: column; gap: 8px;",
				"  box-shadow: 0 6px 24px rgba(0,0,0,0.4); backdrop-filter: blur(6px); }",
				".ff-music-top { display: flex; align-items: center; justify-content: space-between; gap: 8px; }",
				".ff-music-title { font-size: 12px; color: rgba(var(--ff-theme-text), 0.92); white-space: nowrap; overflow: hidden;",
				"  text-overflow: ellipsis; flex: 1; }",
				".ff-music-close { background: transparent; border: none; color: rgba(var(--ff-theme-text-dim), 0.7); cursor: pointer;",
				"  font-size: 14px; line-height: 1; padding: 0 2px; }",
				".ff-music-close:hover { color: rgb(var(--ff-theme-text)); }",
				".ff-music-row { display: flex; gap: 6px; }",
				".ff-music-btn { flex: 1; height: 28px; border-radius: 6px; border: 1px solid rgba(var(--ff-theme-border), 0.3);",
				"  background: rgba(var(--ff-theme-accent), 0.08); color: rgba(var(--ff-theme-text), 0.9); cursor: pointer; font-size: 13px;",
				"  line-height: 1; padding: 0; }",
				".ff-music-btn:hover { background: rgba(var(--ff-theme-accent), 0.18); }",
				".ff-music-mode { flex: 1.4; font-size: 11px; }",

				// ── 播放器：旋转唱片 / 进度条 / 歌单选择 / 封面 ──
				".ff-music-shrink { background: transparent; border: 1px solid rgba(var(--ff-theme-border), 0.3); color: rgba(var(--ff-theme-text-dim), 0.75);",
				"  cursor: pointer; font-size: 11px; line-height: 1; padding: 3px 5px; border-radius: 5px; }",
				".ff-music-shrink:hover { color: rgb(var(--ff-theme-text)); background: rgba(var(--ff-theme-accent), 0.12); }",
				".ff-music-disc-wrap { position: relative; width: 150px; height: 150px; margin: 0 auto; }",
				".ff-music-disc { position: absolute; inset: 0; border-radius: 50%; cursor: pointer;",
				"  background:",
				"    radial-gradient(circle at 50% 50%, rgba(var(--ff-theme-accent), 0.05) 0%, rgba(var(--ff-theme-accent), 0) 58%),",
				"    repeating-radial-gradient(circle at 50% 50%, #101a2c 0 2px, #0a1322 3px 5px);",
				"  box-shadow: 0 6px 22px rgba(0,0,0,0.55), 0 0 0 1px rgba(var(--ff-theme-border), 0.12), 0 0 24px rgba(var(--ff-theme-accent), 0.12);",
				"  animation: ffSpin 8s linear infinite; animation-play-state: paused; }",
				".ff-music-disc.playing { animation-play-state: running; }",
				"@keyframes ffSpin { to { transform: rotate(360deg); } }",
				".ff-music-cover { position: absolute; left: 18%; top: 18%; width: 64%; height: 64%; border-radius: 50%;",
				"  background-size: cover; background-position: center; background-color: #0a1322;",
				"  display: flex; align-items: center; justify-content: center; overflow: hidden;",
				"  box-shadow: inset 0 0 14px rgba(0,0,0,0.65);",
				"  background-image: radial-gradient(circle at 50% 38%, rgba(var(--ff-theme-accent), 0.30), rgba(0,230,118,0.06) 62%, transparent 80%),",
				"    linear-gradient(160deg, #123a28, #072013); }",
				".ff-music-lbl { font-size: 30px; font-weight: 800; color: rgba(var(--ff-theme-text), 0.92);",
				"  text-shadow: 0 0 14px rgba(var(--ff-theme-border), 0.8), 0 1px 1px rgba(0, 0, 0, 0.5), 0 0 2px rgba(0, 0, 0, 0.75) !important; pointer-events: none; line-height: 1; }",
				".ff-music-hub { position: absolute; left: 50%; top: 50%; width: 12px; height: 12px; margin: -6px 0 0 -6px;",
				"  border-radius: 50%; background: rgb(var(--ff-theme-bg)); box-shadow: inset 0 0 0 2px rgba(var(--ff-theme-text), 0.9), 0 0 6px rgba(var(--ff-theme-accent), 0.6); }",
				".ff-music-seek-row { display: flex; align-items: center; gap: 6px; }",
				".ff-music-time { font-size: 10px; color: rgba(var(--ff-theme-text-dim), 0.72); font-variant-numeric: tabular-nums;",
				"  min-width: 30px; text-align: center; }",
				".ff-music-seek { flex: 1; -webkit-appearance: none; appearance: none; height: 4px; border-radius: 2px;",
				"  background: rgba(var(--ff-theme-border), 0.18); outline: none; cursor: pointer; }",
				".ff-music-seek::-webkit-slider-thumb { -webkit-appearance: none; width: 10px; height: 10px; border-radius: 50%;",
				"  background: rgb(var(--ff-theme-accent)); box-shadow: 0 0 6px rgba(var(--ff-theme-accent), 0.7); }",
				".ff-music-seek::-moz-range-thumb { width: 10px; height: 10px; border: none; border-radius: 50%;",
				"  background: rgb(var(--ff-theme-accent)); box-shadow: 0 0 6px rgba(var(--ff-theme-accent), 0.7); }",

				// ── 歌单选择面板（勾选后移除 / 随机，类似壁纸选择器）──
				".ff-ms-picker { position: absolute; right: 0; bottom: calc(100% + 8px); z-index: 93; display: none; flex-direction: column;",
				"  gap: 8px; width: 320px; max-width: calc(100vw - 24px); max-height: calc(100vh - 80px); background: rgba(var(--ff-theme-bg-layer), 0.95);",
				"  border: 1px solid rgba(var(--ff-theme-border), 0.35); border-radius: 10px; padding: 10px; box-shadow: 0 6px 24px rgba(0,0,0,0.45); }",
				".ff-ms-picker.open { display: flex; }",
				".ff-ms-picker-head { display: flex; align-items: center; justify-content: space-between; gap: 8px; }",
				".ff-ms-picker-title { font-size: 12px; letter-spacing: 2px; color: rgba(var(--ff-theme-text-dim), 0.85); }",
				".ff-ms-picker-list { display: flex; flex-direction: column; gap: 4px; align-content: start;",
				"  max-height: min(400px, calc(100vh - 210px)); overflow-y: auto; overscroll-behavior: contain; padding-right: 2px;",
				"  scrollbar-width: thin; scrollbar-color: rgba(var(--ff-theme-accent), 0.35) rgba(255,255,255,0.04); }",
				".ff-ms-picker-list::-webkit-scrollbar { width: 8px; }",
				".ff-ms-picker-list::-webkit-scrollbar-track { background: rgba(255,255,255,0.04); border-radius: 8px; }",
				".ff-ms-picker-list::-webkit-scrollbar-thumb { background: rgba(var(--ff-theme-accent), 0.35); border-radius: 8px; }",
				".ff-ms-picker-list::-webkit-scrollbar-thumb:hover { background: rgba(var(--ff-theme-accent), 0.55); }",
				".ff-ms-item { display: flex; align-items: center; gap: 8px; padding: 7px 8px; border-radius: 6px; cursor: pointer;",
				"  min-width: 0; border: 1px solid rgba(var(--ff-theme-border), 0.15); background: rgba(var(--ff-theme-accent), 0.05); color: rgba(var(--ff-theme-text), 0.9);",
				"  font-size: 12px; transition: border-color 0.15s ease, background 0.15s ease; }",
				".ff-ms-item:hover { border-color: rgba(var(--ff-theme-border), 0.55); background: rgba(var(--ff-theme-accent), 0.1); }",
				".ff-ms-item.checked { border-color: rgb(var(--ff-theme-accent)); background: rgba(var(--ff-theme-accent), 0.14); box-shadow: 0 0 10px rgba(var(--ff-theme-accent), 0.2); }",
				".ff-ms-item.active { border-color: rgba(var(--ff-theme-border), 0.6); color: rgb(var(--ff-theme-accent)); }",
				".ff-ms-check { width: 16px; height: 16px; margin: 0; cursor: pointer; accent-color: rgb(var(--ff-theme-accent-soft)); flex: none; }",
				".ff-ms-item .ttl { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; text-align: left; }",
				".ff-ms-empty { font-size: 11px; color: rgba(var(--ff-theme-text-dim), 0.55); text-align: center; padding: 20px 4px; }",
				".ff-ms-picker-actions { display: flex; gap: 8px; }",

				// ═══ 开屏变身动画（GIF）═══
				".ff-boot { position: fixed; inset: 0; z-index: 99999; background: #03070f; overflow: hidden;",
				"  display: flex; flex-direction: column; align-items: center; justify-content: center;",
				"  opacity: 1; transition: opacity 0.5s ease; }",
				".ff-boot.gone { opacity: 0; pointer-events: none; }",
				".ff-boot::before { content: ''; position: absolute; inset: 0; pointer-events: none;",
				"  background: radial-gradient(70% 55% at 50% 42%, rgba(var(--ff-theme-accent), 0.13), transparent 70%); }",
				".ff-boot .ff-gif { position: relative; max-width: min(94vw, 1000px); max-height: min(70vh, 562px);",
				"  width: auto; height: auto; object-fit: contain; background: #000;",
				"  border-radius: 14px; box-shadow: 0 0 70px rgba(var(--ff-theme-accent), 0.35), 0 0 160px rgba(var(--ff-theme-accent), 0.16);",
				"  opacity: 0; transform: scale(0.95); animation: ffGifIn 0.5s ease forwards; }",
				"@keyframes ffGifIn { to { opacity: 1; transform: scale(1); } }",
				".ff-title { position: relative; margin-top: 30px; font-size: 32px; font-weight: 800; letter-spacing: 14px;",
				"  color: rgb(var(--ff-theme-text)); text-shadow: 0 0 18px rgba(var(--ff-theme-border), 0.9), 0 0 60px rgba(var(--ff-theme-accent), 0.5), 0 1px 1px rgba(0, 0, 0, 0.5), 0 0 2px rgba(0, 0, 0, 0.75) !important;",
				"  opacity: 0; animation: ffFadeIn 0.7s 0.4s ease forwards; }",
				".ff-sub { position: relative; margin-top: 12px; font-size: 14px; letter-spacing: 6px;",
				"  color: rgba(var(--ff-theme-text-dim), 0.85); opacity: 0; animation: ffFadeIn 0.7s 0.7s ease forwards; }",
				"@keyframes ffFadeIn { to { opacity: 1; } }",
				".ff-skip { position: absolute; right: 18px; bottom: 14px; padding: 6px 14px; font-size: 12px;",
				"  letter-spacing: 2px; color: rgba(var(--ff-theme-text-dim), 0.8); background: rgba(var(--ff-theme-border), 0.08);",
				"  border: 1px solid rgba(var(--ff-theme-border), 0.35); border-radius: 6px; cursor: pointer; }",
				".ff-skip:hover { background: rgba(var(--ff-theme-border), 0.16); }",

				"@media (max-width: 640px) {",
				"  .ff-title { font-size: 22px; letter-spacing: 8px; }",
				"  .ff-sub { font-size: 12px; }",
				"}",
				"@media (prefers-reduced-motion: reduce) { .ff-amb { display: none; } .ff-music-disc { animation: none; } }"
			].join("\n");
		}

